
=head1 Messages

The base field class and the field subclasses have some 'built-in' error messages.
These can be modified by setting the 'messages' hashref in the form or the
individual fields.

When a message is retrieved in a field with C<< $field->get_message('upload_file_') >>
for example, the 'get_message' method will look first in user-set field specific messages,
then in user-supplied form messages, finally in messages provided by the field classes.

   package MyApp::Form;
   use HTML::FormHandler::Moose;
   extends 'HTML::FormHandler';

   sub build_messages {
       return { required => '....', my_message => '....' };
   }
   ...
   my $form = MyApp::Form->new( messages => { required => '...', ...} );
   ...
   has_field 'my_field' => ( messages => { required => 'Please provide a my_field' },
       required => 1 );

